### ISSUE TITLE
沒反應

### ISSUE THREAD

**Issue by RootieButler** [jiongjiongJOJO/telegram_info_export#1]
輸入完之後之後給入TG 上的驗證碼，沒反應，沒有EXCEL 檔出來，我再試一次還是要輸TG 上的驗證碼... 有LOG 嗎?? 不知道哪裡出問題了...

**Comment by jiongjiongJOJO** [comment]
> 有LOG 嗎?? 不知道哪裡出問題了...

打开后的黑窗显示的就是日志，可以复制或者截图发出来看下什么原因

**Comment by RootieButler** [comment]
> > 有LOG 嗎?? 不知道哪裡出問題了...
> 
> 打开后的黑窗显示的就是日志，可以复制或者截图发出来看下什么原因

己解決了，我設定了密碼，就是在輸入完TG給的驗證碼的時候，要再輸入密碼，可是您的CODE 裡沒有這個機制所以壞掉，login incomplete然後炸了，不知道哪裡可以加上這個功能.... (TG 上的privacy and security -> two-step verification 中可以設密碼)

```
Telegram is having internal issues AuthRestartError: Restart the authorization process (caused by SendCodeRequest)
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 186, in <lambda>
  File "main.py", line 40, in get_telegram_info
  File "telethon\sync.py", line 39, in syncified
  File "asyncio\base_events.py", line 687, in run_until_complete
  File "telethon\client\auth.py", line 357, in sign_in
  File "telethon\client\users.py", line 30, in __call__
  File "telethon\client\users.py", line 87, in _call
telethon.errors.rpcerrorlist.SessionPasswordNeededError: Two-steps verification is enabled and a password is required (caused by SignInRequest)
```

**Comment by jiongjiongJOJO** [comment]
> 不知道哪裡可以加上這個功能....

这个后续再处理，我抽空先把UI给优化一下吧，太丑了🤣🤣

UI这块我很不熟练，慢慢摸索吧。

**Comment by RootieButler** [comment]
> > 不知道哪裡可以加上這個功能....
> 
> 这个后续再处理，我抽空先把UI给优化一下吧，太丑了🤣🤣
> 
> UI这块我很不熟练，慢慢摸索吧。

UI 己經很好看了~ 真的~ 😁♥️

**Comment by jiongjiongJOJO** [comment]
v1.1.0 release版本已经解决此问题，详情请查看 [v1.1.0](https://github.com/jiongjiongJOJO/telegram_info_export/releases/tag/v1.1.0)。
